//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSTest.OnlineTradingApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeTransaction
    {
        public int Id { get; set; }
        public int TransactionType { get; set; }
        public int CustomerId { get; set; }
        public int StockId { get; set; }
        public int StockCount { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual TradeTransaction TradeTransaction1 { get; set; }
        public virtual TradeTransaction TradeTransaction2 { get; set; }
    }
}
